# Generated by Django 5.1.4 on 2024-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
