# Generated by Django 5.1.4 on 2024-12-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.userprofile'),
        ),
    ]
